use yew_router::prelude::*;

#[derive(Clone, Routable, PartialEq)]
pub enum Route {
    #[at("/")]
    Landing,
    #[at("/docs")]
    Home,
    #[at("/docs/buttons")]
    Buttons,
    #[at("/docs/text-fields")]
    TextFields,
    #[at("/docs/selection")]
    Selection,
    #[at("/docs/slider")]
    Slider,
    #[at("/docs/chips")]
    Chips,
    #[at("/docs/cards")]
    Cards,
    #[at("/docs/progress")]
    Progress,
    #[at("/docs/badges")]
    Badges,
    #[at("/docs/dialog")]
    Dialog,
    #[at("/docs/list")]
    List,
    #[at("/docs/tabs")]
    Tabs,
    #[at("/docs/typography")]
    Typography,
    #[at("/docs/box")]
    Box,
    #[at("/docs/grid")]
    Grid,
    #[at("/docs/split-buttons")]
    SplitButtons,
    #[at("/docs/select-textarea")]
    SelectTextarea,
    #[at("/docs/accordions")]
    Accordions,
    #[at("/docs/toggle-buttons")]
    ToggleButtons,
    #[at("/docs/alert-box")]
    AlertBox,
    #[at("/docs/skeleton")]
    Skeleton,
    #[at("/docs/breadcrumb")]
    Breadcrumb,
    #[at("/docs/image-list")]
    ImageList,
    #[at("/docs/avatars-shapes")]
    AvatarsShapes,
    #[at("/docs/shape-gallery")]
    ShapeGallery,
    #[at("/docs/steppers")]
    Steppers,
    #[at("/docs/tables")]
    Tables,
    #[at("/docs/navigation-drawer")]
    NavigationDrawer,
    #[at("/docs/bottom-sheet")]
    BottomSheet,
    #[at("/docs/theme-tokens")]
    ThemeTokens,
    #[at("/docs/code-view")]
    CodeView,
    #[at("/docs/carousel")]
    Carousel,
    #[at("/docs/navigation-rail")]
    NavigationRail,
    #[at("/docs/navigation-bar")]
    NavigationBar,
    #[at("/docs/tab-bar")]
    TabBar,
    #[at("/docs/ripple")]
    Ripple,
    #[at("/docs/icon")]
    Icon,
    #[at("/docs/menu")]
    Menu,
    #[at("/docs/snackbar")]
    Snackbar,
    #[at("/docs/tooltip")]
    Tooltip,
    #[at("/docs/toolbar")]
    Toolbar,
    #[at("/docs/top-app-bar")]
    TopAppBar,
    #[at("/docs/divider")]
    Divider,
    #[at("/docs/container")]
    Container,
    #[at("/docs/spacer")]
    Spacer,
    #[at("/docs/showcase/email")]
    ShowcaseEmail,
    #[at("/docs/showcase/login")]
    ShowcaseLogin,
    #[at("/docs/showcase/admin")]
    ShowcaseAdmin,
    #[at("/docs/showcase/settings")]
    ShowcaseSettings,
    #[at("/docs/showcase/ecommerce")]
    ShowcaseEcommerce,
    #[at("/docs/showcase/blog")]
    ShowcaseBlog,
    #[not_found]
    #[at("/404")]
    NotFound,
}
